//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralLoadTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentralLoadTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TraceData xmlns=&quot;http://tempuri.org/TracePersistence.xsd&quot;&gt;
        ///  &lt;Header&gt;
        ///    &lt;TraceProvider name=&quot;Microsoft SQL Server&quot; MajorVersion=&quot;12&quot; MinorVersion=&quot;0&quot; BuildNumber=&quot;4213&quot; /&gt;
        ///    &lt;ServerInformation name=&quot;WLKCND4071HPV\SQL2014&quot; /&gt;
        ///    &lt;ProfilerUI&gt;
        ///      &lt;OrderedColumns&gt;
        ///        &lt;ID&gt;27&lt;/ID&gt;
        ///        &lt;ID&gt;1&lt;/ID&gt;
        ///        &lt;ID&gt;10&lt;/ID&gt;
        ///        &lt;ID&gt;6&lt;/ID&gt;
        ///        &lt;ID&gt;11&lt;/ID&gt;
        ///        &lt;ID&gt;18&lt;/ID&gt;
        ///        &lt;ID&gt;16&lt;/ID&gt;
        ///        &lt;ID&gt;17&lt;/ID&gt;
        ///        &lt;ID&gt;13&lt;/ID&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
    }
}
